[DEFAULT]

title = Glossarator 1.3
greeting = GLOSSARATOR (c)2017 v.1.3
farewell = See you, space cowboy.

path = ../glossaries
active_glossary = MAIN

max_results = 25

colour0 = #fff5b4
#	Gold: 255,245,180
colour1 = #05d2ff
#	Blue: 5,210,255
colour2 =  #ff326e
#	Pink: 255,50,110
#background = #323232
#	Charcoal: 50,50,50